services:
  db:
    image: postgres:18-alpine
    container_name: swd_postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: swd_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASS:-password}@db:5432/${DB_NAME:-sawasdee_db}
      - JWT_SECRET=${JWT_SECRET:-my_super_secret_jwt_key_for_dev}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db

volumes:
  postgres_data: